version: '3'
# To make the external links work they need to be on the same network
networks:
  test_network:
      external: true

services:
  BBB:
    networks:
        test_network:
            aliases:
                - BBB
    image: python
    command: ping AAA
