version: '3'
# To make the external links work they need to be on the same network
networks:
  test_network:
      external: true

services:
  AAA:
    networks:
        test_network:
            aliases:
                - AAA
    image: python
    command: sleep infinity
